apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-service
    app: votingapp
spec:
  type: ClusterIP
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: votingapp
    name: pod-postgresql
    tier: back-end
