apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: votingapp
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    app: votingapp
    name: pod-redis
    tier: back-end
