apiVersion: v1
kind: Pod
metadata:
  name: pod-resultapp
  labels:
    name: pod-resultapp
    app: votingapp
    tier: front-end
spec:
  containers:
    - name: redisapp-container
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80
