apiVersion: v1
kind: Pod
metadata:
  name: pod-worker
  labels:
    name: pod-worker
    app: votingapp
    tier: back-end
spec:
  containers:
    - name: worker-container
      image: kodekloud/examplevotingapp_worker:v1
