apiVersion: v1
kind: Service
metadata:
  name: resultapp-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30005
  selector:
    name: pod-resultapp
    app: votingapp
    tier: front-end
