apiVersion: apps/v1
kind: Deployment
metadata:
  name: resultapp-deployment
  labels:
    name: resultapp-deployment
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pod-resultapp
      app: votingapp
      tier: front-end
  template:
    metadata:
      name: pod-resultapp
      labels:
        name: pod-resultapp
        app: votingapp
        tier: front-end
    spec:
      containers:
        - name: redisapp-container
          image: kodekloud/examplevotingapp_result:v1
          ports:
            - containerPort: 80
